spring.application.name=art
server.port=8081

cloudinary.cloud-name=dwbqrriji
cloudinary.api-key=751234634775427
cloudinary.api-secret=87kjM_sSK7WVHDVid6ff8kf3DMQ

jwt.refreshExpirationMs=2592000000
jwt.accessExpirationMs=2592000000
jwt.accessSecret=ivjZbDgNdnLo7y2RX79f2UGM9VZeUukflPWBjVvbcZg0XULRRBoMZpoVS1UZu4Y2SULeOKh1tUgeGxi850zkbQ==
jwt.refreshSecret=5qiVycQif5R8Eliep/7ZFbIxBgd5d284IHy9uqCXH0Sr9eBziV6rTFfK74MQHPFkZ+SaiSw7Uo96WeXG5OtYVA==

spring.datasource.url=jdbc:postgresql://localhost:5432/artdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG